spring:
  application:
    name: jylx_product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jiyilvxing
    url: jdbc:mysql://JYLX-k8s5:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: JYLX-k8s5
    port: 5672
    username: guest
    password: guest
  redis:
    host: JYLX-k8s5
    port: 6379
  jpa:
    show-sql: true
girl: 18