spring:
  application:
    name: jylx_order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jiyilvxing
    url: jdbc:mysql://JYLX-k8s5:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: JYLX-k8s5
    port: 5672
    username: guest
    password: guest
  redis:
    host: JYLX-k8s5
    port: 6379
env:
  test13
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  