spring:
  application:
    name: jylx_product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jiyilvxing
    url: jdbc:mysql://192.168.16.141:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.16.141
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.16.141
    port: 6379
  jpa:
    show-sql: true