spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jiyilvxing
    url: jdbc:mysql://127.0.0.1:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379