spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.141:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
    username: root
    password: jiyilvxing
  rabbitmq:
    host: jylx-k8s5
    port: 5672
    username: guest
    password: guest
  redis:
    host: jylx-k8s5
    port: 6379
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    base-url: http://jylx-k8s5:9411/
    #如果项目中没有使用rabbitmq，可以不用配置，如果有，默认为rabbit，而不是web
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  