spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.141:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
    username: root
    password: jiyilvxing
  rabbitmq:
    host: 192.168.16.141
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.16.141
    port: 6379
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true