spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jylx-k8s5:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
    username: root
    password: jiyilvxing
  rabbitmq:
    host: jylx-k8s5
    port: 5672
    username: guest
    password: guest
  redis:
    host: jylx-k8s5
    port: 6379
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    base-url: http://jylx-k8s5:9411/
    #如果项目中没有使用rabbitmq，可以不用配置，如果有，默认为rabbit，而不是web
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
#fegin超时配置,以上注释为老版本
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  