spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.host}:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
    username: root
    password: jiyilvxing
  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${redis.host}
    port: 6379
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  instance:
    hostname: product
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/