spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jylx-k8s5:3306/jiyilvxing?characterEncoding=utf-8&useSSL=false
    username: root
    password: jiyilvxing
  redis:
    host: jylx-k8s5
    port: 6379
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true